//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeWiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
