//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeWiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleTable
    {
        public int Module_Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Credits { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<int> ClassHoursPerWeek { get; set; }
        public Nullable<int> SelfStudyHours { get; set; }
        public Nullable<int> RemainingWeekHours { get; set; }
        public Nullable<int> ProgressBarPercentage { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public Nullable<int> StudiedHours { get; set; }
    
        public virtual Semester Semester { get; set; }
    }
}
