//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeWiz
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudyTable
    {
        [Key]
        public int Study_Id { get; set; }
        public int ClassHoursPerWeek { get; set; }
        public int SelfStudyHours { get; set; }
        public int StudiedHours { get; set; }
        public int RemainingWeekHours { get; set; }
        public int Module_Id { get; set; }
        public Nullable<decimal> ProgressBarPercentage { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
    
        public virtual ModuleTable ModuleTable { get; set; }
    }
}
